services:
  backend:
    build:
      context: .
      dockerfile: project/Dockerfile
    working_dir: /app/final-project/
    container_name: csci-716-final-project
    volumes:
      - ../csci-716-final-project:/app/final-project/
